### ISSUE TITLE
跑不起来呢

### ISSUE THREAD

**Issue by toutouli** [Sky-David-Ye/Jianshu2Markdown#1]
Python 3.5.1 报错，我不会python，看了源码也不知道什么问题
```shell
Traceback (most recent call last):
  File "jianshu.py", line 139, in <module>
    main()
  File "jianshu.py", line 135, in main
    client.start()
  File "jianshu.py", line 33, in start
    end = self.get_profile_end()
  File "jianshu.py", line 30, in get_profile_end
    return int(end.group(1))
AttributeError: 'NoneType' object has no attribute 'group'
````

**Comment by Sky-David-Ye** [comment]
修复了。你再试试

**Comment by toutouli** [comment]
嗯，可以了，谢谢！请问是什么问题呢？我正在学习python

**Comment by Sky-David-Ye** [comment]
是我没有处理简书页面只有一页的情况，这样正则就匹配不了，返回None。
